### ISSUE TITLE
MySQL Out of Sync

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#29]
We've only had the server up a night! No restarts, and we have some players nuggets being reset to 0! This can't happen, they are playing to earn nuggets for prizes. Theres some faulty logic on how nuggets are saved/set somewhere. 
There is a HELL of a lot of errors coming out of CoreArena https://www.dropbox.com/s/2ah5qsm15y6qqqa/latest.log?dl=0

Cant link to pastebin as the sheer number of errors from CoreArena makes the logs over 5mb per day.

**Comment by kangarko** [comment]
Hey,

maybe this is linked with https://github.com/kangarko/CoreArena/issues/28, can you please test without MySQL only using the local data.db file located in GameAPI/ folder?

I will fix that error soon, I apology for the inconvenience.

**Comment by FrozenBeard** [comment]
Im happy to use the data.db, IF I can copy that data to mysql afterwards, I just need to know the password from #22 then I will be able to import it!

**Comment by FrozenBeard** [comment]
Did you look at your Logic to why it would reset to 0? it should NEVER update a record to 0, it should only increment.

**Comment by kangarko** [comment]
Sorry once again, there is no password from my side. It is you who configure the plugin to connect to MySQL, and also the database itself. I recommend you take contact with your server hosting.

Nuggets are decremented when users purchase rewards, so yes, they go down to zero if the reward cost is equal user's Nugget status.

**Comment by kangarko** [comment]
Sorry once again, there is no password from my side. It is you who configure the plugin to connect to MySQL, and also the database itself. I recommend you take contact with your server hosting.

Nuggets are decremented when users purchase rewards, so yes, they go down to zero if the reward cost is equal user's Nugget status.

**Comment by FrozenBeard** [comment]
The default plugin, when you generate configs, creates a **data.db** file, I have not edited a single file, This is all defaults. I can not open it to view its contents without a password.
There for I cannot switch between this data.db and the MySQL as I cannot view the contents, You created this database on startup, I do not know your process for generating the database, but it included setting a password to it.

As for Nuggets and rewards, I have not a SINGLE reward setup as I wanted to collect data on the nuggets being collected. I just had a game RIGHT now with players, were all on teamspeak like 15 of us, one player said out loud before the game "I have 43 Nuggets" After the round he got 7 nuggets, but his /ma rewards STILL stated 43. There is a BUG with your collection of nugget points, there was no error in the console, there is no issue with my database.

I even created a Reddit thread requesting people look at my MySQL database setup from a group of other server owners that run giant servers, top comment "_Both are faults of bad programmers imo._"
https://www.reddit.com/r/admincraft/comments/7bdw64/can_someone_please_look_at_my_mariadbmysql_config/?ref=share&ref_source=link

Again, don't palm this one off on me, I can see there are issues with it, I have told you, my players are getting extremely frustrated, and they will not play the arena plugin I bought as their nuggets are not getting saved, which means no rewards, which makes it entirely pointless. 

This is a major flaw with the plugin that needs to be fixed.

**Comment by FrozenBeard** [comment]
The default plugin, when you generate configs, creates a **data.db** file, I have not edited a single file, This is all defaults. I can not open it to view its contents without a password.
There for I cannot switch between this data.db and the MySQL as I cannot view the contents, You created this database on startup, I do not know your process for generating the database, but it included setting a password to it.

As for Nuggets and rewards, I have not a SINGLE reward setup as I wanted to collect data on the nuggets being collected. I just had a game RIGHT now with players, were all on teamspeak like 15 of us, one player said out loud before the game "I have 43 Nuggets" After the round he got 7 nuggets, but his /ma rewards STILL stated 43. There is a BUG with your collection of nugget points, there was no error in the console, there is no issue with my database.

I even created a Reddit thread requesting people look at my MySQL database setup from a group of other server owners that run giant servers, top comment "_Both are faults of bad programmers imo._"
https://www.reddit.com/r/admincraft/comments/7bdw64/can_someone_please_look_at_my_mariadbmysql_config/?ref=share&ref_source=link

Again, don't palm this one off on me, I can see there are issues with it, I have told you, my players are getting extremely frustrated, and they will not play the arena plugin I bought as their nuggets are not getting saved, which means no rewards, which makes it entirely pointless. 

This is a major flaw with the plugin that needs to be fixed.

**Comment by kangarko** [comment]
Oh I see now where the misunderstand was! The ".db" file extension is fake, in reality, we use a simple YAML storage. You can simply right click the file and open it with a text editor such as Notepad++.

For the MySQL problems, I have tested the connection and there seemed to be an issue when the data.db in GameAPI folder contains Nuggets while the MySQL don't. This have been fixed, please as always, test the next version and let me know if it works for you.

**Comment by kangarko** [comment]
P.S: If you are curious what's happening with the MySQL, you can set the "Debugger" to "[mysql]" in settings.yml

**Comment by FrozenBeard** [comment]
This is still an issue, I set my staff and players to test this after the update and its still not saving Nuggets correctly.
Here is a video a player made showing it not incrementing https://www.youtube.com/watch?v=aHGFJfVt-RU

1 person had their nuggets reset to 0, Some people it keeps the old nuggets and does not increment those won on the next game. We had a game where someone won 7 nuggets and their maximum increased by 1!
We also cant tell if its saving properly on death and not when they survive and the round ends, or if it happens both when they loose all their lives and when they survive and get teleported.

**Comment by FrozenBeard** [comment]
This is still a massive issue, and this issue alone has made nobody want to use our arena, putting all the time and effort into our building an entire server around this plugin useless, without the points, we can award rewards. I enabled the debug on the MySQL but there seems to be no errors, so its a logic error in the programming.
Its random, some people will get ALL of their nuggets reset to 0, the majority it will be fine, and it will be random if you get your data wiped.
This is so bad, nobody wants to play the mini-game with fear all their efforts will be wiped.
This needs to be fixed, im at the end of my tether now, this just needs to be fixed. this has completely ruined our entire event, nobody will use it because of this bug.

**Comment by kangarko** [comment]
I am on it, came home today, in the meanwhile please test the console debug output when you set the "Debugger" to "[mysql]" in settings.yml.

**Comment by FrozenBeard** [comment]
Yup, I've had it on a while, but the issue is nobody wants to play because of this bug. So its impossible to get testing happening.

**Comment by kangarko** [comment]
Could you possibly look up if still have the output from the console from the time when it was one? The reason why I am asking is that it will show exactly what Nugget value we sent to MySQL and vice versa, and possibly reveal the cause of the problem soonest possible. Thanks!

**Comment by kangarko** [comment]
Hello,

I had time and done few-hours-long testing of various scenarios. I sadly could not reproduce the bug, the only problem I encountered was the /ma nuggets command not working correctly after /reload, that has been fixed in the next version.

Normal arena finish:
![a](https://i.imgur.com/aOE6QLg.png)

Leave command
![b](https://i.imgur.com/VXB8bqx.png)

Leave command (2)
![c](https://i.imgur.com/GrMf0WX.png)

That's why it is critically important for me that you enable the Debug to [mysql] in settings.yml  to get the debug messages just like I had in the screenshots above, and we can find where exactly it is happening. Thank you.

**Comment by LogGits** [comment]
Are you using PaperSpigot by any chance @FrozenBeard?

**Comment by FrozenBeard** [comment]
@LogGits yes.
Full log of recent games: https://pastebin.com/P01jdMN1
I cant see any errors, since I added prizes i've had players playing recently and ive had an insane amount of complains about nuggets just going missing.
So RIGHT now, like Right now, I had 2 players loose nuggets Look at that log, the players are SimbadTiger and Volpex_.
Im at the point now where im going to just bin this plugin and find another, i cannot believe the amount of tickets ive had to make about how broken this plugin is.

**Comment by FrozenBeard** [comment]
its not always 0, most of the time they are just set to a lower number
Simbad sent me this too, to say when it happened: 
Simbad_Tiger: [16:32:06] [main/INFO]: [CHAT] Arena // You received 21 Nuggets and have 120 Nuggets. Go spend them on /arena rewards!
[6:03 PM] Simbad_Tiger: [18:41:32] [main/INFO]: [CHAT] Arena // You received 12 Nuggets and have 66 Nuggets. Go spend them on /arena rewards!

**Comment by kangarko** [comment]
FrozenBeard, the only cause I see it possibly can be, since we do synchronize the database on each login, is that your MySQL database takes longer to connect to then the amount of time the player takes to swap servers. In this case, any form of cache would be useless because we would have the old amount of nuggets on the other server which would again cause trouble. I honestly don't know what next steps should I take, I advise you to ask out your hosting's provider to point out if there can be a performance issue with the database.

**Comment by FrozenBeard** [comment]
As I have said, I run a dedicated server, so I have MariaDB installed myself, there really isn't much too it, its a direct connection nothing else in the way, no VM, no other services just a plane old firewall with the allowed ports.
I also sync Chat across servers, Permissions with luckperms just fine.
Maybe have a talk with the Luckperms dev see how he does it? Hes a solid developer and I dont have any issues with ranks or permissions syncing perfectly fine.

**Comment by FrozenBeard** [comment]
My players are getting utterly frustrated with this constantly, we are all sick to death of it not working.
here is a video of it not working made by a player.
https://www.youtube.com/watch?v=FDfcRI7ol2g&feature=youtu.be

**Comment by kangarko** [comment]
Hey, sorry I haven't been able to help you out. I asked moderators and fellow developers in my team to help out. Should you wish to be fully refunded as this is understandable please let me know. Otherwise I will do best in my efforts to have this resolved by Sunday before I travel back home.

**Comment by FrozenBeard** [comment]
Im still hoping you will be able to fix it, its the only thing letting the entire plugin down to the point its unusable, everything else is amazing, I just need a working system to collect points and spend them on the survival.

**Comment by kangarko** [comment]
@FrozenBeard please post me your full CoreArena/ folder in a ZIP, make sure you remove MySQL information. It would be the best if you could send both folders from both servers.

**Comment by kangarko** [comment]
@FrozenBeard I used this forenoon to test it heavily. Good news is I came with new logic that haven't been tested, please answer the questions below so it will make it easier to track down. Bad news is, I am leaving country and coming back 28th December. I advise to disable MySQL on that server and just let players collect their Nuggets and maybe use a plugin for physical currency - golden nuggets, so the players can purchase the nuggets in the rewards menu on that server, and then it would be converted into Vault / normal Economy which would be synchronized by an economy plugin like feConomy, EssentialsEco or etc.

* Are more arenas run at the same time when this is happening?
* Is the issue present with MySQL disabled ?

**Comment by FrozenBeard** [comment]
@kangarko 

- I only have 1 arena, events.piratemc.com a Halloween arena.
- I have only tried it with MySQL, How would I go about converting the nuggets people have already into flatfile?
- How would I setup "using nuggets to buy currency" I would want them to use a second currency so its separate from my currency currency, just incase they find a way to farm unlimited money easy. There are a metric ton of "token" plugins that use MySQL out there on spigot, how would I go about using one of these?
- Do you still need my CoreArena settings in a Zip?

**Comment by kangarko** [comment]
@FrozenBeard,

I had a few days to really dive deep into this problem. I was finally able to reproduce using a slow third party database where the synchronization issues would show up. Before I was not able to reproduce because I tested locally on my computer where the mysql database delay is virtually 0, or using the corearena test server which also has extremely fast connection.

There are two new options, Aggresive (you should not need this unless you specifically want to save nuggets to mysql each time a player's nugget status changes, i.e. he buys a reward, next arena wave, etc.), and the Delay_Ticks, as specified below. Enable the Debug to [mysql], see what your delay is, and adjust accordingly.
![a](https://i.imgur.com/MkUSaMY.png)

Let me know if anything arises again. 
Closing in faith that this has been resolved.
