### ISSUE TITLE
1.16.1: Nuggets are not saving correctly

### ISSUE THREAD

**Issue by NightFuryStrike** [kangarko/CoreArena#320]
Greetings, my players have noticed an issue where Nuggets are not correctly saving after an arena game.

For example if you get 50 nuggets from an arena, you are able to spend them, but it appears to get reset to 0 after you join and play another arena, rejoin the server, or reboot the server. They also don't appear in the data.db file either after inspecting it.

Additionally, it appears the nuggets value on the main menu of /arena rewards is different than the nuggets value in the sub-menus (class selection and other rewards), they seem to show different amounts after an arena.

I unfortunately do not have time right now to make a more detailed bug report, but I can provide much more detail and videos at a later date if needed.

**Comment by kangarko** [comment]
Thanks,

Can you please provide ZIP folder with your whole settings so I can reproduce?

**Comment by christaylor201** [comment]
I can confirm the same issue on PaperMC 1.15.2 build 385 with only CoreArena 2.7.3 installed.

**Comment by LeehamElectronics** [comment]
I can also confirm this with PaperMC 1.15.2

**Comment by LeehamElectronics** [comment]
As a temporary fix I started using SQL storage and the latest version of CoreArena and the "nuggets" issue is fixed. However another issue I fixed was disabling my FTP drive for CoreArena. I found that every time I restated CoreArena all the changes I made in game to Arenas such as Procedural damage all disappeared! This was extremely annoying but I think the issue was that I had FTP access open to the CoreArena files, so if anyone is having these issues, use SQL and DONT use FTP on CoreArena files!
Hope this helps someone.

**Comment by LeehamElectronics** [comment]
Also the issue of showing different values of nuggets in menus was also resolved using SQL which I just realized.

**Comment by kangarko** [comment]
Thank you, I fixed these issues, apology for the inconvenience!

**Comment by LeehamElectronics** [comment]
Unfortunately the issue has arisen again and all players lost there nuggets after the server restarted. @kangarko  You said you fixed the issue, is that in an upcoming update or am i doing something wrong? I am using SQL for storage. It seems to only reset nuggets on server restarts. I am using CoreArena 2.7.4
Cheers

**Comment by LeehamElectronics** [comment]
Oh just saw you released a new version, ill test it now and see if it fixes it.

**Comment by christaylor201** [comment]
The nuggets are now saved properly, thank you very much for the quick fix! However, the amount of them in the main rewards menu still doesn't update, only in the sub-menus.

**Comment by kangarko** [comment]
Thank you I will fix that!
